package com.example.kiosk6;

public enum StageType {

    // STAGE 동작권한 지정
    STAGE1_CHOOSE_MENU,
    STAGE2_CHOOSE_ITEM,
    STAGE3_ADD_SHOPPINGBAG,
    STAGE4_CHOOSE_MENU_PAYMENT,
    STAGE5_PROCEED_PAYMENT,
    STAGE6_CHOOSE_DISCOUNT,
    EXIT
}
